[package]
name = "vru-noise"
version = "1.1.1"
authors = ["Vladislav Melnik <vlad9486@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Noise handshake protocol implemented in Rust"
repository = "https://github.com/vlad9486/vru"

[dependencies.rac]
version = "1.1"

[dependencies.zeroize]
version = "1.1"

[dependencies.byteorder]
version = "1.3"

[dependencies.aead]
version = "0.3"

[dependencies.chacha20poly1305]
version = "0.5"
optional = true

[dependencies.aes-gcm]
version = "0.6"
optional = true

[dependencies.digest]
version = "0.9"

[dependencies.hkdf]
version = "0.9.0-alpha.0"

[dependencies.generic-array]
version = "0.14"

[dependencies.either]
version = "1.5"

[dependencies.hex]
version = "0.4"

[dependencies.vru-noise-macros]
version = "1.0"
optional = true

[dependencies.futures]
version = "0.3"

[dev-dependencies.rac]
version = "1.1"
features = ["secp256k1", "curve25519-dalek"]

[dev-dependencies.secp256k1]
version = "0.17"
features = ["rand-std"]

[dev-dependencies.curve25519-dalek]
version = "2.1"

[dev-dependencies.sha2]
version = "0.9"

[dev-dependencies.chacha20poly1305]
version = "0.5"

[dev-dependencies.aes-gcm]
version = "0.6"

[dev-dependencies.tokio]
version = "0.2"
features = ["io-util", "tcp", "test-util", "macros", "rt-core"]

[dev-dependencies.vru-noise-macros]
version = "1.0"

[features]
std = []
