[package]
name = "vru-session"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@protonmail.com>"]
edition = "2018"

[dependencies]
rac = "1.1"
futures = "0.3"
either = "1.5"

[features]
std = []
